name: BedWars0721
version: '${version}'
main: cc.bw0721.BedWars0721
api-version: '1.13'
depend: [BedWars1058]

commands:
  bw0721:
    permission: bw0721.admin

permissions:
  bw0721.admin:
    default: op
  bw0721.command.reload:
    default: op
  bw0721.command.addarena:
    default: op
